**Creating a 1D Array**

In [76]:
import numpy as np

an_array = np.array([1,3,5,7, 9])

print(an_array)

print(type(an_array))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [77]:
print(an_array.shape)

(5,)


**Creating 2D arrays**

In [78]:
twoD_array = np.array([[11,12,13], [21,22,23]])

print(twoD_array)
print(twoD_array.shape)

[[11 12 13]
 [21 22 23]]
(2, 3)


**Many ways to create nd arrays**

In [79]:
ex1 = np.zeros([2,2])
print(ex1)

[[ 0.  0.]
 [ 0.  0.]]


In [80]:
ex2 = np.full((2,2), 9)
print(ex2)

[[9 9]
 [9 9]]


In [81]:
ex3 = np.eye(3,2)
print(ex3)

[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]]


In [82]:
ex4 = np.ones((1,2))
print(ex4)

[[ 1.  1.]]


In [83]:
ex5 = np.random.random((2,2))
print(ex5)

[[ 0.73620031  0.35784814]
 [ 0.10322418  0.29482833]]


**Slice Indexing**

In [84]:
an_array = np.array([[11,12,13],[21,22,23], [31,32,33]])
a_slice = an_array[0:2, 1:3] #a_slice is a ref to a subset of an_array
print(a_slice)

[[12 13]
 [22 23]]


In [85]:
#to copy a slice 
another_array = np.array(an_array[:2, 1:3])
print(another_array)

[[12 13]
 [22 23]]


In [86]:
#a_slice is ref 
a_slice[0,0] = 102
another_array[0,0] = 1020 
print(an_array)
print(a_slice)
print(another_array)

[[ 11 102  13]
 [ 21  22  23]
 [ 31  32  33]]
[[102  13]
 [ 22  23]]
[[1020   13]
 [  22   23]]


**Indexing using lists**

In [87]:
row_indices = np.array([0,1,2])
col_indices = np.array([0,1,2])
an_array[row_indices, col_indices] += 1000
print(an_array)

[[1011  102   13]
 [  21 1022   23]
 [  31   32 1033]]


**Boolean Indexing**

In [91]:
filter = (an_array > 25)
filter

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True,  True]], dtype=bool)

In [92]:
print(an_array[filter])

[1011  102 1022   31   32 1033]


In [93]:
print(an_array[an_array>15])

[1011  102   21 1022   23   31   32 1033]


In [94]:
print(an_array)

[[1011  102   13]
 [  21 1022   23]
 [  31   32 1033]]


**Modifying array based on boolean indexing**

In [95]:
an_array[an_array%2==0] += 100
print(an_array)

[[1011  202   13]
 [  21 1122   23]
 [  31  132 1033]]


**nd array data types**

In [102]:
#auto assigned data type by python
int_array = np.array([1,2,3,4])
print(int_array.dtype)
float_array = np.array([1.1,2.2,3.3,4.4])
print(float_array.dtype)

int64
float64


In [104]:
#explicitly specified type
int_array_with_float = np.array([1.1, 2.2, 3.3], dtype=np.int64)
print(int_array_with_float)
print(int_array_with_float.dtype)

[1 2 3]
int64
