**Creating a 1D Array**

In [1]:
import numpy as np

an_array = np.array([1,3,5,7, 9])

print(an_array)

print(type(an_array))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)

(5,)


**Creating 2D arrays**

In [3]:
twoD_array = np.array([[11,12,13], [21,22,23]])

print(twoD_array)
print(twoD_array.shape)

[[11 12 13]
 [21 22 23]]
(2, 3)


**Many ways to create nd arrays**

In [4]:
ex1 = np.zeros([2,2])
print(ex1)

[[ 0.  0.]
 [ 0.  0.]]


In [5]:
ex2 = np.full((2,2), 9)
print(ex2)

[[9 9]
 [9 9]]


In [6]:
ex3 = np.eye(3,2)
print(ex3)

[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]]


In [7]:
ex4 = np.ones((1,2))
print(ex4)

[[ 1.  1.]]


In [8]:
ex5 = np.random.random((2,2))
print(ex5)

[[ 0.43280162  0.73880861]
 [ 0.80257671  0.73115143]]


**Slice Indexing**

In [9]:
an_array = np.array([[11,12,13],[21,22,23], [31,32,33]])
a_slice = an_array[0:2, 1:3] #a_slice is a ref to a subset of an_array
print(a_slice)

[[12 13]
 [22 23]]


In [10]:
#to copy a slice 
another_array = np.array(an_array[:2, 1:3])
print(another_array)

[[12 13]
 [22 23]]


In [11]:
#a_slice is ref 
a_slice[0,0] = 102
another_array[0,0] = 1020 
print(an_array)
print(a_slice)
print(another_array)

[[ 11 102  13]
 [ 21  22  23]
 [ 31  32  33]]
[[102  13]
 [ 22  23]]
[[1020   13]
 [  22   23]]


**Indexing using lists**

In [12]:
row_indices = np.array([0,1,2])
col_indices = np.array([0,1,2])
an_array[row_indices, col_indices] += 1000
print(an_array)

[[1011  102   13]
 [  21 1022   23]
 [  31   32 1033]]


**Boolean Indexing**

In [13]:
filter = (an_array > 25)
filter

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True,  True]], dtype=bool)

In [14]:
print(an_array[filter])

[1011  102 1022   31   32 1033]


In [15]:
print(an_array[an_array>15])

[1011  102   21 1022   23   31   32 1033]


In [16]:
print(an_array)

[[1011  102   13]
 [  21 1022   23]
 [  31   32 1033]]


**Modifying array based on boolean indexing**

In [17]:
an_array[an_array%2==0] += 100
print(an_array)

[[1011  202   13]
 [  21 1122   23]
 [  31  132 1033]]


**nd array data types**

In [18]:
#auto assigned data type by python
int_array = np.array([1,2,3,4])
print(int_array.dtype)
float_array = np.array([1.1,2.2,3.3,4.4])
print(float_array.dtype)

int64
float64


In [19]:
#explicitly specified type
int_array_with_float = np.array([1.1, 2.2, 3.3], dtype=np.int64)
print(int_array_with_float)
print(int_array_with_float.dtype)

[1 2 3]
int64


**Arithmetic operations on nd arrays**

In [21]:
x = np.array([100, 200, 300, 400])
y = np.array([500, 600, 700, 800])

print(x + y)
print()
print(np.add(x,y))

[ 600  800 1000 1200]

[ 600  800 1000 1200]


In [23]:
print(x - y)
print()
print(np.subtract(x,y))

[-400 -400 -400 -400]

[-400 -400 -400 -400]


In [25]:
print(x*y)
print()
print(np.multiply(x,y))

[ 50000 120000 210000 320000]

[ 50000 120000 210000 320000]


In [26]:
print(np.exp(x))
print(np.log(y))

[  2.68811714e+043   7.22597377e+086   1.94242640e+130   5.22146969e+173]
[ 6.2146081   6.39692966  6.55108034  6.68461173]


In [ ]:
print(m)